services:
  fl_server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FL_NUM_ROUNDS=10
      - FL_STRATEGY=fednova
      - FL_ROBUST_AGGREGATOR=median

  institution_a:
    build:
      context: .
      dockerfile: clients/institution_a/Dockerfile
    volumes:
      - ./data/client_partitions/tech:/data:ro
    environment:
      - CLIENT_ID=A
      - TARGET_EPSILON=1.0
      - SERVER_HOST=fl_server
      - LOCAL_DP_NOISE_MULTIPLIER=0.0
      - MALICIOUS_ATTACK=none
    depends_on:
      - fl_server

  institution_b:
    build:
      context: .
      dockerfile: clients/institution_b/Dockerfile
    volumes:
      - ./data/client_partitions/finance:/data:ro
    environment:
      - CLIENT_ID=B
      - TARGET_EPSILON=1.0
      - SERVER_HOST=fl_server
      - LOCAL_DP_NOISE_MULTIPLIER=0.0
      - MALICIOUS_ATTACK=none
    depends_on:
      - fl_server

  institution_c:
    build:
      context: .
      dockerfile: clients/institution_c/Dockerfile
    volumes:
      - ./data/client_partitions/healthcare_industrials:/data:ro
    environment:
      - CLIENT_ID=C
      - TARGET_EPSILON=1.0
      - SERVER_HOST=fl_server
      - LOCAL_DP_NOISE_MULTIPLIER=0.0
      - MALICIOUS_ATTACK=none
    depends_on:
      - fl_server

  blockchain_node:
    build:
      context: .
      dockerfile: blockchain/Dockerfile.ganache
    ports:
      - "8545:8545"

  oracle_api:
    build:
      context: .
      dockerfile: oracle/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data/test_locked:/data/test:ro

  mlflow:
    build:
      context: .
      dockerfile: mlflow_server/Dockerfile
    ports:
      - "5000:5000"

  dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./reports:/app/reports:ro
      - ./models:/app/models:ro
    depends_on:
      - oracle_api
      - blockchain_node
